### ISSUE TITLE
Upgrade github_api dependency to current one.

### ISSUE THREAD

**Issue by piotrmurach** [piotrmurach/github_cli#24]
This would probably break some of the apis, thus would involve updating tests and numerous commands.

**Comment by piotrmurach** [comment]
@zhenglaizhang I'm going to be adding issues on the tracker so that we can divide work between us. This one is quiet chunky but very important. Just let me know what you fancy doing.

**Comment by zhenglaizhang** [comment]
@piotrmurach So coooool we are going to upgrade the github_api, great effort!! 👍 

How about assigning following sub commands (I just run `gcil` and paste the posterior sub commands here :)) to me, I will test these commands, update if anything broken, and add appropriate tests for them.

```bash
   search       Leverage Search API
   star         Leverage Starring API
   stat         Leverage Statistics API
   status       Leverage Statuses API
   tag          Leverage Tags API
   team         Leverage Teams API
   tree         Leverage Trees API
   user         Leverage Users API
   version      Display Github CLI version.
   watch        Leverage Watching API
   whoami       Print the username config to standard out
```
