### ISSUE TITLE
[Feature Request] gcli delete command

### ISSUE THREAD

**Issue by Kristinita** [piotrmurach/github_cli#27]
### 1. Request

It would be nice, if you will be add command `gcli delete` for delete multiple repositories.

### 2. Justification

I have many forks. Now I can delete my unusable forks only [**use web-interface**](http://stackoverflow.com/a/23914426/5951529). It may take a lot of time for many repositories.

### 3. Desirable behavior

```shell
gcli delete repo1 repo2 repo3

Are you sure, that you want to delete these repositories? [Y/N]

y

Your repositories successfully deleted.
```

### 4. Examples on other apps

See [**sepehr function**](https://github.com/github/hub/issues/494#issuecomment-271180227) for delete repositories, but I don't understand, how I can use it in Windows.

Thanks.

**Comment by piotrmurach** [comment]
Hi Sasza, 

Thank you for using this library. Your request looks good to me but I will be perfectly honest I won't work on it. I simply have no capacity this month. I'm focusing my energy on releaseing `tty-prompt` and `github_api`. My spare time is limited. I would definietly encourage you give it a go and try to implement what you need. Regarding semantics I would probably suggest to do:
```ruby
gcli repo delete repo1 repo2 repo3 
```
