### ISSUE TITLE
Tabular output from "gcli repo ls -u wycats --format=csv"

### ISSUE THREAD

**Issue by psprint** [piotrmurach/github_cli#31]
Hello,
I run the example command:

```sh
gcli repo ls -u wycats --format=csv
```

and it still appears as tables.

**Comment by titaniumbones** [comment]
(same issue for me, arch linux, version 0.6.2). I'm hoping to get a list of forks in a form I can use in scripts, so it would be great to have another format available. thanks!

**Comment by rubensayshi** [comment]
works fine if you `gcli config core.format csv` :/

**Comment by piotrmurach** [comment]
Fixed and will be part of `0.7.0` release.
