### ISSUE TITLE
❗️❗️❗️Check it out❗️❗️❗️

### ISSUE THREAD

**Issue by ashanaakh** [piotrmurach/github_cli#35]
I've created the best cli for github https://github.com/ashanaakh/gitius. Check it out! 😉

**Comment by piotrmurach** [comment]
Normally, I don't try to feed trols but this is such unique and interesting case on many levels that the curious part got better of me.

It is clear that your trying to garner support of your library but at what cost? It shows little thought on your part as to what effect this will have on the maintainer of the library and what signals your are sending to future developers that may consider working on your open source. 

You're basically interested in glory-seeking behaviour and wish to increase your 'fame' by trolling other similar projects. Have you thought about open source and what it truly means? Collaboration is one thing that springs to mind. You have missed one of the most valuable opportunities there is, which is to collaborate on more established project and not only help it grow but create new opportunity for yourself to learn and grow. Instead, you choose to try to 'score' off another project.

I really hope that the 'better' part of you will learn from this experience and you will spend your energies in more productive ways in the future. You have already wasted enough of my time!
